#!/bin/bash
echo
echo "[i] compiling src ..."
javac -Xlint:unchecked -cp gson-2.11.0.jar:. Core.java \
	&& javac -cp . Test.java
if [ $? -eq 0 ]
then
	echo "[i] running test ..."
	java -cp gson-2.11.0.jar:. Test
	if [ $? -eq 0 ]
	then
		echo "[i] all test passed!"
	fi
fi
echo
rm -rf *.class
